# Generated by Django 5.2.16 on 2026-07-10 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('semester', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('total_lectures', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LectureSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecture_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Lab', 'Lab')], default='Theory', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_slots', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_slots', to='timetable.subject')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
