# Generated by Django 5.2.16 on 2026-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureslot',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lectureslot',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lectureslot',
            name='lecture_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial')], default='Theory', max_length=15),
        ),
    ]
