# Generated by Django 5.2.16 on 2026-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_lectureslot_building_lectureslot_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cancelled_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
