# Generated by Django 5.2.16 on 2026-07-10 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('time_difference', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('lecture_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='timetable.lectureslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='timetable.subject')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
                'unique_together': {('student', 'lecture_slot', 'date')},
            },
        ),
    ]
