# Generated by Django 5.2.16 on 2026-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Cancelled', 'Cancelled'), ('Holiday', 'Holiday')], max_length=10),
        ),
    ]
