# Generated by Django 5.2.16 on 2026-07-10 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_liked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_length', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Detailed', 'Detailed')], default='Medium', max_length=20)),
                ('response_style', models.CharField(choices=[('Professional', 'Professional'), ('Friendly', 'Friendly'), ('Concise', 'Concise'), ('Technical', 'Technical'), ('Simple Language', 'Simple Language')], default='Friendly', max_length=30)),
                ('preferred_goal', models.PositiveIntegerField(default=75)),
                ('enable_suggestions', models.BooleanField(default=True)),
                ('enable_daily_summary', models.BooleanField(default=True)),
                ('enable_attendance_warnings', models.BooleanField(default=True)),
                ('enable_weekly_insights', models.BooleanField(default=True)),
                ('enable_monthly_report', models.BooleanField(default=True)),
                ('enable_smart_recommendations', models.BooleanField(default=True)),
                ('auto_generate_reports', models.BooleanField(default=True)),
                ('voice_assistant', models.BooleanField(default=False)),
                ('preferred_reminder_time', models.CharField(choices=[('5 Minutes', '5 Minutes'), ('10 Minutes', '10 Minutes'), ('15 Minutes', '15 Minutes'), ('30 Minutes', '30 Minutes'), ('Custom', 'Custom')], default='15 Minutes', max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
                ('theme_preference', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('System', 'System')], default='System', max_length=20)),
                ('allow_attendance_data', models.BooleanField(default=True)),
                ('allow_timetable_analysis', models.BooleanField(default=True)),
                ('allow_report_analysis', models.BooleanField(default=True)),
                ('allow_analytics', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation'),
        ),
        migrations.DeleteModel(
            name='AIMemory',
        ),
    ]
