# Generated by Django 5.2.16 on 2026-07-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_chatmessage_user_chatmessage_is_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipreferences',
            name='college_latitude',
            field=models.FloatField(default=19.076),
        ),
        migrations.AddField(
            model_name='aipreferences',
            name='college_longitude',
            field=models.FloatField(default=72.8777),
        ),
        migrations.AddField(
            model_name='aipreferences',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='aipreferences',
            name='geofencing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
